export interface Product {
  id: string
  name: string
  category: string
  subcategory: string
  description: string
  features: string[]
  sizes: string[]
  images: string[]
  featured?: boolean
}

export const categories = {
  sportswear: {
    name: "Sportswear",
    subcategories: [
      "Soccer Kits",
      "Tracksuits",
      "Rain Jackets",
      "Bubble Jackets",
      "Polo Shirts",
      "Rugby",
      "American Football",
      "Netball",
      "Half Zip Top",
      "Motocross Suits",
      "Ice Hockey Kits",
      "Racing Jackets",
    ],
  },
  streetwear: {
    name: "Streetwear",
    subcategories: [
      "Hoodies",
      "Graphic T-Shirts",
      "Oversize Hoodies",
      "Flannel Shirts",
      "Long Sleeve Tees",
      "Cargo Pants",
      "Baggy Jeans",
      "Ripped Jeans",
      "Shorts",
      "Caps",
      "Cross Body Bags",
    ],
  },
  gloves: {
    name: "Gloves",
    subcategories: [
      "Weightlifting Gloves",
      "Cycling Gloves",
      "Soccer Gloves",
      "Baseball Batting Gloves",
      "American Football Gloves",
      "Motorbike Gloves",
      "Sim Racing Gloves",
      "Motocross Gloves",
      "Hunting Gloves",
      "Golf Gloves",
    ],
  },
}

export const products: Product[] = [
  // SPORTSWEAR
  {
    id: "soccer-kit-pro",
    name: "Pro Soccer Kit",
    category: "sportswear",
    subcategory: "Soccer Kits",
    description: "Premium performance soccer kit designed for professional athletes. Features moisture-wicking fabric and ergonomic design for maximum mobility on the field.",
    features: ["Moisture-wicking fabric", "Breathable mesh panels", "Reinforced stitching", "Custom sublimation printing"],
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    images: ["/products/soccer-kit-1.jpg", "/products/soccer-kit-2.jpg"],
    featured: true,
  },
  {
    id: "tracksuit-elite",
    name: "Elite Tracksuit",
    category: "sportswear",
    subcategory: "Tracksuits",
    description: "Luxury tracksuit combining style and functionality. Perfect for warm-ups, training, or casual streetwear.",
    features: ["Premium polyester blend", "Full zip jacket", "Tapered fit pants", "Hidden pockets"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    images: ["/products/tracksuit-1.jpg", "/products/tracksuit-2.jpg"],
    featured: true,
  },
  {
    id: "rain-jacket-storm",
    name: "Storm Rain Jacket",
    category: "sportswear",
    subcategory: "Rain Jackets",
    description: "Waterproof rain jacket with advanced breathability. Stay dry during intense training sessions in any weather.",
    features: ["Waterproof membrane", "Sealed seams", "Adjustable hood", "Reflective details"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    images: ["/products/rain-jacket-1.jpg", "/products/rain-jacket-2.jpg"],
  },
  {
    id: "bubble-jacket-winter",
    name: "Winter Bubble Jacket",
    category: "sportswear",
    subcategory: "Bubble Jackets",
    description: "Insulated bubble jacket for extreme cold conditions. Premium down filling with water-resistant outer shell.",
    features: ["Down insulation", "Water-resistant", "Packable design", "Inner pockets"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    images: ["/products/bubble-jacket-1.jpg", "/products/bubble-jacket-2.jpg"],
  },
  {
    id: "polo-performance",
    name: "Performance Polo",
    category: "sportswear",
    subcategory: "Polo Shirts",
    description: "Classic polo shirt with modern performance features. Ideal for golf, tennis, or casual business settings.",
    features: ["Quick-dry fabric", "UV protection", "Anti-odor technology", "Ribbed collar"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    images: ["/products/polo-1.jpg", "/products/polo-2.jpg"],
  },
  {
    id: "rugby-jersey-pro",
    name: "Pro Rugby Jersey",
    category: "sportswear",
    subcategory: "Rugby",
    description: "Heavy-duty rugby jersey built to withstand the toughest matches. Reinforced construction in high-stress areas.",
    features: ["Reinforced stitching", "Durable fabric", "Sublimated graphics", "Grip collar"],
    sizes: ["S", "M", "L", "XL", "XXL", "3XL"],
    images: ["/products/rugby-1.jpg", "/products/rugby-2.jpg"],
    featured: true,
  },
  {
    id: "american-football-jersey",
    name: "American Football Jersey",
    category: "sportswear",
    subcategory: "American Football",
    description: "Professional-grade American football jersey with premium sublimation printing and reinforced seams.",
    features: ["Mesh body", "Reinforced shoulders", "Custom numbering", "Moisture management"],
    sizes: ["S", "M", "L", "XL", "XXL", "3XL"],
    images: ["/products/football-1.jpg", "/products/football-2.jpg"],
  },
  {
    id: "netball-dress",
    name: "Netball Dress",
    category: "sportswear",
    subcategory: "Netball",
    description: "Stylish netball dress with integrated shorts. Designed for maximum movement and comfort on the court.",
    features: ["Built-in shorts", "Lightweight fabric", "Stretch material", "Custom printing"],
    sizes: ["XS", "S", "M", "L", "XL"],
    images: ["/products/netball-1.jpg", "/products/netball-2.jpg"],
  },
  {
    id: "half-zip-training",
    name: "Half Zip Training Top",
    category: "sportswear",
    subcategory: "Half Zip Top",
    description: "Versatile half zip training top perfect for layering. Sleek design with athletic fit.",
    features: ["Quarter zip", "Thumb holes", "Raglan sleeves", "Reflective logo"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    images: ["/products/halfzip-1.jpg", "/products/halfzip-2.jpg"],
  },
  {
    id: "motocross-suit",
    name: "Motocross Racing Suit",
    category: "sportswear",
    subcategory: "Motocross Suits",
    description: "Full protection motocross suit with ventilation panels. Built for extreme off-road racing conditions.",
    features: ["CE-rated armor", "Ventilation panels", "Stretch panels", "Triple stitching"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    images: ["/products/motocross-1.jpg", "/products/motocross-2.jpg"],
  },
  {
    id: "ice-hockey-jersey",
    name: "Ice Hockey Jersey",
    category: "sportswear",
    subcategory: "Ice Hockey Kits",
    description: "Professional ice hockey jersey with fight strap and reinforced elbows. Full customization available.",
    features: ["Fight strap", "Reinforced elbows", "Mesh inserts", "Sublimated crests"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    images: ["/products/hockey-1.jpg", "/products/hockey-2.jpg"],
  },
  {
    id: "racing-jacket-speed",
    name: "Speed Racing Jacket",
    category: "sportswear",
    subcategory: "Racing Jackets",
    description: "Lightweight racing jacket with aerodynamic design. Perfect for motorsports and cycling.",
    features: ["Aerodynamic fit", "Perforated panels", "CE-rated", "Removable liner"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    images: ["/products/racing-1.jpg", "/products/racing-2.jpg"],
  },

  // STREETWEAR
  {
    id: "hoodie-essential",
    name: "Essential Hoodie",
    category: "streetwear",
    subcategory: "Hoodies",
    description: "Premium cotton hoodie with relaxed fit. The perfect everyday essential for any wardrobe.",
    features: ["100% cotton", "Kangaroo pocket", "Ribbed cuffs", "Embroidered logo"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    images: ["/products/hoodie-1.jpg", "/products/hoodie-2.jpg"],
    featured: true,
  },
  {
    id: "graphic-tee-urban",
    name: "Urban Graphic Tee",
    category: "streetwear",
    subcategory: "Graphic T-Shirts",
    description: "Bold graphic t-shirt with premium screen printing. Stand out with unique streetwear designs.",
    features: ["Premium cotton", "Screen printed", "Oversized fit", "Pre-shrunk"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    images: ["/products/graphic-tee-1.jpg", "/products/graphic-tee-2.jpg"],
    featured: true,
  },
  {
    id: "oversize-hoodie-cloud",
    name: "Cloud Oversize Hoodie",
    category: "streetwear",
    subcategory: "Oversize Hoodies",
    description: "Ultra-soft oversized hoodie for maximum comfort. Dropped shoulders and extended length.",
    features: ["Fleece lined", "Dropped shoulders", "Extended length", "Heavy weight"],
    sizes: ["S", "M", "L", "XL"],
    images: ["/products/oversize-hoodie-1.jpg", "/products/oversize-hoodie-2.jpg"],
  },
  {
    id: "flannel-check",
    name: "Classic Check Flannel",
    category: "streetwear",
    subcategory: "Flannel Shirts",
    description: "Heavyweight flannel shirt with classic check pattern. Layer it up for the perfect street look.",
    features: ["100% cotton", "Button down", "Chest pockets", "Curved hem"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    images: ["/products/flannel-1.jpg", "/products/flannel-2.jpg"],
  },
  {
    id: "longsleeve-basics",
    name: "Basics Long Sleeve",
    category: "streetwear",
    subcategory: "Long Sleeve Tees",
    description: "Essential long sleeve tee in premium cotton. Perfect for layering or worn alone.",
    features: ["Soft cotton", "Relaxed fit", "Ribbed cuffs", "Side splits"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    images: ["/products/longsleeve-1.jpg", "/products/longsleeve-2.jpg"],
  },
  {
    id: "cargo-tactical",
    name: "Tactical Cargo Pants",
    category: "streetwear",
    subcategory: "Cargo Pants",
    description: "Utility cargo pants with multiple pockets. Military-inspired design meets street style.",
    features: ["Multi-pocket", "Adjustable straps", "Durable ripstop", "Relaxed fit"],
    sizes: ["28", "30", "32", "34", "36", "38"],
    images: ["/products/cargo-1.jpg", "/products/cargo-2.jpg"],
    featured: true,
  },
  {
    id: "baggy-jeans-vintage",
    name: "Vintage Baggy Jeans",
    category: "streetwear",
    subcategory: "Baggy Jeans",
    description: "90s-inspired baggy jeans with authentic vintage wash. The comeback of classic street style.",
    features: ["Wide leg", "Vintage wash", "Heavy denim", "Five pocket"],
    sizes: ["28", "30", "32", "34", "36"],
    images: ["/products/baggy-1.jpg", "/products/baggy-2.jpg"],
  },
  {
    id: "ripped-jeans-distressed",
    name: "Distressed Ripped Jeans",
    category: "streetwear",
    subcategory: "Ripped Jeans",
    description: "Hand-distressed ripped jeans with authentic worn look. Premium denim construction.",
    features: ["Hand distressed", "Slim fit", "Stretch denim", "Whisker details"],
    sizes: ["28", "30", "32", "34", "36"],
    images: ["/products/ripped-1.jpg", "/products/ripped-2.jpg"],
  },
  {
    id: "shorts-mesh",
    name: "Mesh Athletic Shorts",
    category: "streetwear",
    subcategory: "Shorts",
    description: "Breathable mesh shorts perfect for sports or street. Above-knee length with side pockets.",
    features: ["Mesh fabric", "Elastic waist", "Side pockets", "Quick dry"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    images: ["/products/shorts-1.jpg", "/products/shorts-2.jpg"],
  },
  {
    id: "cap-snapback",
    name: "Classic Snapback Cap",
    category: "streetwear",
    subcategory: "Caps",
    description: "Premium snapback cap with structured crown. Embroidered logo and adjustable closure.",
    features: ["Structured crown", "Flat brim", "Snapback closure", "Embroidered"],
    sizes: ["One Size"],
    images: ["/products/cap-1.jpg", "/products/cap-2.jpg"],
  },
  {
    id: "crossbody-tactical",
    name: "Tactical Cross Body Bag",
    category: "streetwear",
    subcategory: "Cross Body Bags",
    description: "Tactical cross body bag with multiple compartments. Perfect for everyday carry essentials.",
    features: ["Multiple compartments", "Adjustable strap", "Water resistant", "Quick release"],
    sizes: ["One Size"],
    images: ["/products/crossbody-1.jpg", "/products/crossbody-2.jpg"],
  },

  // GLOVES
  {
    id: "weightlifting-power",
    name: "Power Weightlifting Gloves",
    category: "gloves",
    subcategory: "Weightlifting Gloves",
    description: "Heavy-duty weightlifting gloves with wrist support. Premium leather palm for maximum grip.",
    features: ["Leather palm", "Wrist wrap", "Breathable back", "Reinforced stitching"],
    sizes: ["S", "M", "L", "XL"],
    images: ["/products/weightlifting-1.jpg", "/products/weightlifting-2.jpg"],
    featured: true,
  },
  {
    id: "cycling-aero",
    name: "Aero Cycling Gloves",
    category: "gloves",
    subcategory: "Cycling Gloves",
    description: "Aerodynamic cycling gloves with gel padding. Touchscreen-compatible fingertips.",
    features: ["Gel padding", "Touchscreen tips", "Breathable mesh", "Reflective strips"],
    sizes: ["S", "M", "L", "XL"],
    images: ["/products/cycling-gloves-1.jpg", "/products/cycling-gloves-2.jpg"],
  },
  {
    id: "soccer-goalkeeper",
    name: "Pro Goalkeeper Gloves",
    category: "gloves",
    subcategory: "Soccer Gloves",
    description: "Professional goalkeeper gloves with 4mm latex palm. Maximum grip in all conditions.",
    features: ["4mm latex palm", "Finger spines", "Wrist strap", "Breathable backhand"],
    sizes: ["7", "8", "9", "10", "11"],
    images: ["/products/goalkeeper-1.jpg", "/products/goalkeeper-2.jpg"],
    featured: true,
  },
  {
    id: "baseball-batting",
    name: "Pro Batting Gloves",
    category: "gloves",
    subcategory: "Baseball Batting Gloves",
    description: "Premium batting gloves with Cabretta leather palm. Enhanced grip and feel at the plate.",
    features: ["Cabretta leather", "Perforated fingers", "Neoprene wrist", "Digital palm"],
    sizes: ["S", "M", "L", "XL"],
    images: ["/products/batting-1.jpg", "/products/batting-2.jpg"],
  },
  {
    id: "american-football-receiver",
    name: "Elite Receiver Gloves",
    category: "gloves",
    subcategory: "American Football Gloves",
    description: "Sticky receiver gloves with maximum grip technology. NFL-grade performance.",
    features: ["Sticky palm", "Compression fit", "Wrist closure", "Breathable mesh"],
    sizes: ["S", "M", "L", "XL"],
    images: ["/products/receiver-1.jpg", "/products/receiver-2.jpg"],
  },
  {
    id: "motorbike-racing",
    name: "Racing Motorbike Gloves",
    category: "gloves",
    subcategory: "Motorbike Gloves",
    description: "CE-certified motorbike gloves with carbon knuckle protection. Kangaroo leather palm.",
    features: ["Carbon knuckles", "Kangaroo leather", "Touchscreen tips", "Double stitched"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    images: ["/products/motorbike-1.jpg", "/products/motorbike-2.jpg"],
  },
  {
    id: "sim-racing-pro",
    name: "Pro Sim Racing Gloves",
    category: "gloves",
    subcategory: "Sim Racing Gloves",
    description: "Professional sim racing gloves for maximum wheel grip. Ultra-thin for precise control.",
    features: ["Ultra-thin", "Silicone grip", "Breathable", "Seamless palm"],
    sizes: ["S", "M", "L", "XL"],
    images: ["/products/sim-racing-1.jpg", "/products/sim-racing-2.jpg"],
  },
  {
    id: "motocross-mx",
    name: "MX Motocross Gloves",
    category: "gloves",
    subcategory: "Motocross Gloves",
    description: "Lightweight motocross gloves with silicone grip pattern. Maximum control and comfort.",
    features: ["Silicone grip", "Stretch mesh", "Reinforced palm", "Hook closure"],
    sizes: ["S", "M", "L", "XL"],
    images: ["/products/mx-gloves-1.jpg", "/products/mx-gloves-2.jpg"],
  },
  {
    id: "hunting-camo",
    name: "Camo Hunting Gloves",
    category: "gloves",
    subcategory: "Hunting Gloves",
    description: "Insulated hunting gloves with realistic camo pattern. Touchscreen tips for device use.",
    features: ["Insulated", "Camo pattern", "Touchscreen tips", "Waterproof"],
    sizes: ["S", "M", "L", "XL"],
    images: ["/products/hunting-1.jpg", "/products/hunting-2.jpg"],
  },
  {
    id: "golf-premium",
    name: "Premium Golf Gloves",
    category: "gloves",
    subcategory: "Golf Gloves",
    description: "Premium Cabretta leather golf gloves. Superior feel and grip for the perfect swing.",
    features: ["Cabretta leather", "Perforated", "Ball marker", "Stretch fit"],
    sizes: ["S", "M", "ML", "L", "XL"],
    images: ["/products/golf-1.jpg", "/products/golf-2.jpg"],
  },
]

export function getProductById(id: string): Product | undefined {
  return products.find((p) => p.id === id)
}

export function getProductsByCategory(category: string): Product[] {
  return products.filter((p) => p.category === category)
}

export function getFeaturedProducts(): Product[] {
  return products.filter((p) => p.featured)
}

export function getRelatedProducts(product: Product, limit = 4): Product[] {
  return products
    .filter((p) => p.id !== product.id && p.category === product.category)
    .slice(0, limit)
}
